// src/components/Customer/CustomerDashboard.tsx
import React, { useState } from 'react';
import { Calendar, Package, CreditCard, Bell, User, BarChart3 } from 'lucide-react';
import CalendarBooking from './CalendarBooking';
import SubscriptionManager from './SubscriptionManager';

const CustomerDashboard: React.FC = () => {
  const [activeTab, setActiveTab] = useState('calendar');

  const tabs = [
    { id: 'calendar', name: 'Book Milk', icon: Calendar },
    { id: 'subscription', name: 'Subscriptions', icon: Package },
    { id: 'billing', name: 'Billing', icon: CreditCard },
    { id: 'profile', name: 'Profile', icon: User }
  ];

  const stats = [
    { label: 'This Month Orders', value: '24', color: 'bg-blue-500' },
    { label: 'Total Spent', value: '₹672', color: 'bg-green-500' },
    { label: 'Active Subscriptions', value: '2', color: 'bg-purple-500' },
    { label: 'Next Delivery', value: 'Tomorrow', color: 'bg-orange-500' }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-cyan-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          {stats.map((stat, index) => (
            <div key={index} className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl border border-blue-100 p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600 mb-1">{stat.label}</p>
                  <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
                </div>
                <div className={`w-12 h-12 ${stat.color} rounded-xl flex items-center justify-center`}>
                  <BarChart3 className="h-6 w-6 text-white" />
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Navigation Tabs */}
        <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl border border-blue-100 mb-8">
          <div className="flex space-x-1 p-2">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`
                    flex-1 flex items-center justify-center space-x-2 py-3 px-4 rounded-xl transition-all
                    ${activeTab === tab.id 
                      ? 'bg-gradient-to-r from-blue-500 to-cyan-500 text-white shadow-lg' 
                      : 'text-gray-600 hover:bg-gray-50'}
                  `}
                >
                  <Icon className="h-5 w-5" />
                  <span className="font-medium">{tab.name}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Tab Content */}
        <div className="space-y-8">
          {activeTab === 'calendar' && <CalendarBooking />}
          {activeTab === 'subscription' && <SubscriptionManager />}
          {activeTab === 'billing' && <BillingHistory />}
          {activeTab === 'profile' && <ProfileSettings />}
        </div>
      </div>
    </div>
  );
};

const BillingHistory: React.FC = () => {
  const bills = [
    { id: 1, month: 'November 2024', amount: 672, status: 'Paid', date: '2024-11-01' },
    { id: 2, month: 'October 2024', amount: 680, status: 'Paid', date: '2024-10-01' },
    { id: 3, month: 'September 2024', amount: 650, status: 'Paid', date: '2024-09-01' }
  ];

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-blue-100 p-6">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">Billing History</h2>
      
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-gray-200">
              <th className="text-left py-3 px-4 font-medium text-gray-700">Period</th>
              <th className="text-left py-3 px-4 font-medium text-gray-700">Amount</th>
              <th className="text-left py-3 px-4 font-medium text-gray-700">Status</th>
              <th className="text-left py-3 px-4 font-medium text-gray-700">Date</th>
              <th className="text-left py-3 px-4 font-medium text-gray-700">Action</th>
            </tr>
          </thead>
          <tbody>
            {bills.map((bill) => (
              <tr key={bill.id} className="border-b border-gray-100 hover:bg-gray-50">
                <td className="py-4 px-4">{bill.month}</td>
                <td className="py-4 px-4 font-semibold">₹{bill.amount}</td>
                <td className="py-4 px-4">
                  <span className="bg-green-100 text-green-800 px-2 py-1 rounded-full text-xs font-medium">
                    {bill.status}
                  </span>
                </td>
                <td className="py-4 px-4 text-gray-600">{bill.date}</td>
                <td className="py-4 px-4">
                  <button className="text-blue-600 hover:text-blue-800 font-medium">
                    Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

const ProfileSettings: React.FC = () => {
  return (
    <div className="bg-white rounded-2xl shadow-xl border border-blue-100 p-6">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">Profile Settings</h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Full Name</label>
          <input 
            type="text" 
            defaultValue="John Doe"
            className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
          />
        </div>
        
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Email</label>
          <input 
            type="email" 
            defaultValue="john@example.com"
            className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
          />
        </div>
        
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Phone</label>
          <input 
            type="tel" 
            defaultValue="+91 9876543210"
            className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
          />
        </div>
        
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Delivery Address</label>
          <textarea 
            defaultValue="123 Main Street, Apartment 4B, Chennai - 600001"
            className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
            rows={3}
          />
        </div>
      </div>
      
      <div className="mt-6">
        <button className="bg-gradient-to-r from-blue-500 to-cyan-500 text-white px-6 py-3 rounded-xl hover:from-blue-600 hover:to-cyan-600 transition-all">
          Update Profile
        </button>
      </div>
    </div>
  );
};

export default CustomerDashboard;

// src/app/features/customer/customer-dashboard/customer-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTabsModule } from '@angular/material/tabs';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { CalendarBookingComponent } from '../calendar-booking/calendar-booking.component';
import { SubscriptionManagerComponent } from '../subscription-manager/subscription-manager.component';

@Component({
  selector: 'app-customer-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatTabsModule,
    MatCardModule,
    MatIconModule,
    CalendarBookingComponent,
    SubscriptionManagerComponent
  ],
  template: `
    <div class="min-h-screen p-8">
      <div class="max-w-7xl mx-auto">
        
        <!-- Stats Cards -->
        <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          @for (stat of stats; track stat.label) {
            <mat-card class="glass-effect card-shadow p-6 hover-lift">
              <div class="flex items-center justify-between">
                <div>
                  <p class="text-sm text-gray-600 mb-1">{{ stat.label }}</p>
                  <p class="text-2xl font-bold text-gray-900">{{ stat.value }}</p>
                </div>
                <div [class]="stat.color" class="w-12 h-12 rounded-xl flex items-center justify-center">
                  <mat-icon class="text-white">{{ stat.icon }}</mat-icon>
                </div>
              </div>
            </mat-card>
          }
        </div>

        <!-- Navigation Tabs -->
        <mat-card class="glass-effect card-shadow mb-8">
          <mat-tab-group [(selectedIndex)]="selectedTabIndex" class="p-4">
            <mat-tab>
              <ng-template mat-tab-label>
                <mat-icon class="mr-2">calendar_today</mat-icon>
                Book Milk
              </ng-template>
              <app-calendar-booking></app-calendar-booking>
            </mat-tab>
            
            <mat-tab>
              <ng-template mat-tab-label>
                <mat-icon class="mr-2">subscriptions</mat-icon>
                Subscriptions
              </ng-template>
              <app-subscription-manager></app-subscription-manager>
            </mat-tab>
            
            <mat-tab>
              <ng-template mat-tab-label>
                <mat-icon class="mr-2">payment</mat-icon>
                Billing
              </ng-template>
              <div class="p-6">
                <h2 class="text-2xl font-bold text-gray-900 mb-6">Billing History</h2>
                <div class="space-y-4">
                  @for (bill of billingHistory; track bill.id) {
                    <div class="border border-gray-200 rounded-xl p-4 flex justify-between items-center">
                      <div>
                        <p class="font-medium">{{ bill.month }}</p>
                        <p class="text-sm text-gray-600">{{ bill.date }}</p>
                      </div>
                      <div class="text-right">
                        <p class="font-bold">₹{{ bill.amount }}</p>
                        <span class="bg-green-100 text-green-800 px-2 py-1 rounded-full text-xs">{{ bill.status }}</span>
                      </div>
                    </div>
                  }
                </div>
              </div>
            </mat-tab>
            
            <mat-tab>
              <ng-template mat-tab-label>
                <mat-icon class="mr-2">person</mat-icon>
                Profile
              </ng-template>
              <div class="p-6">
                <h2 class="text-2xl font-bold text-gray-900 mb-6">Profile Settings</h2>
                <p class="text-gray-600">Profile management coming soon...</p>
              </div>
            </mat-tab>
          </mat-tab-group>
        </mat-card>
      </div>
    </div>
  `,
  styles: [`
    .glass-effect {
      background: rgba(255, 255, 255, 0.8);
      backdrop-filter: blur(10px);
      border: 1px solid rgba(59, 130, 246, 0.1);
    }
    .card-shadow {
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
    }
    .hover-lift {
      transition: transform 0.2s ease-in-out;
    }
    .hover-lift:hover {
      transform: translateY(-2px);
    }
  `]
})
export class CustomerDashboardComponent implements OnInit {
  selectedTabIndex = 0;

  stats = [
    { label: 'This Month Orders', value: '24', color: 'bg-blue-500', icon: 'shopping_cart' },
    { label: 'Total Spent', value: '₹672', color: 'bg-green-500', icon: 'account_balance_wallet' },
    { label: 'Active Subscriptions', value: '2', color: 'bg-purple-500', icon: 'subscriptions' },
    { label: 'Next Delivery', value: 'Tomorrow', color: 'bg-orange-500', icon: 'local_shipping' }
  ];

  billingHistory = [
    { id: 1, month: 'November 2024', amount: 672, status: 'Paid', date: '2024-11-01' },
    { id: 2, month: 'October 2024', amount: 680, status: 'Paid', date: '2024-10-01' },
    { id: 3, month: 'September 2024', amount: 650, status: 'Paid', date: '2024-09-01' }
  ];

  ngOnInit(): void {
    // Initialize component
  }
}
